# Generated by Django 3.1.4 on 2021-10-18 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(choices=[(0, 'Junior'), (1, 'Mid Level'), (1, 'Senior')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Annual Salary', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.IntegerField(choices=[(0, 'Full Time'), (1, 'Part Time')], default=0, null=True),
        ),
    ]
